# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-08-18 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flow_info', models.CharField(max_length=128)),
                ('match', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=128)),
            ],
        ),
    ]
