# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-08-18 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='action',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='table',
            name='flow_info',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='table',
            name='match',
            field=models.CharField(max_length=1024),
        ),
    ]
