# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-08-18 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QosApp', '0002_auto_20200818_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='action',
            new_name='instruction',
        ),
        migrations.AddField(
            model_name='table',
            name='node',
            field=models.CharField(default='', max_length=128),
        ),
    ]
