# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-08-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QosApp', '0003_auto_20200818_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='flow_info',
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='table',
            name='priority',
            field=models.CharField(default='', max_length=128),
        ),
    ]
