# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-08-18 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QosApp', '0004_auto_20200818_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='node',
        ),
        migrations.AddField(
            model_name='table',
            name='flow_name',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='table',
            name='flow_node',
            field=models.CharField(default='', max_length=256),
        ),
    ]
