# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-08-18 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QosApp', '0005_auto_20200818_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='flow_name',
            new_name='flow',
        ),
    ]
