# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-08-19 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QosApp', '0006_auto_20200818_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter', models.CharField(max_length=256)),
                ('meterType', models.CharField(max_length=256)),
                ('bandRate', models.CharField(max_length=256)),
                ('bandSize', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='inport',
            field=models.CharField(default='', max_length=64),
        ),
    ]
